#!/usr/bin/env python
"""chesspuz -> Android. Copies the app into android/app, builds the APK in the WSL build box
(the Ubuntu distro "dd-android" on D:, shared with Digit Defender), installs and runs it on the
USB phone.

    python android\\sync.py                  sync (default): refresh android/app, bump VERSION
    python android\\sync.py all              sync + build + install + run + logs
    python android\\sync.py setup            one-time: toolchain in the WSL box (uv, Python 3.11,
                                            PySide6 deploy tool, Qt Android wheels)
    python android\\sync.py build            build the signed release APK (--debug: a debuggable
                                            one); the first build compiles CPython 3.11 and
                                            friends (~10 min), later ones take a few minutes
    python android\\sync.py clean build      regenerate the buildozer project and rebuild
    python android\\sync.py install run      adb install + launch on the phone
    python android\\sync.py logs             app lines from logcat  (--follow 20 = 20 s live)
    python android\\sync.py status           what is set up, connected and built

Options: --version X.Y.Z (else the patch number bumps on every sync), --no-bump, --no-db
         (leave the puzzle database out), --db PATH (bundle this database), --debug, --serial S,
         --follow N, --verbose (every build line; android/build.log always has everything).
Windows-side helper: stdlib plus PySide6 (draws the icon, present for the app anyway).
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import time
import urllib.request
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent  # the repository
AND = ROOT / "android"
APP = AND / "app"
WSL_DIR = Path(r"D:\WSL")
DISTRO = "dd-android"
ROOTFS_URL = (
    "https://cloud-images.ubuntu.com/wsl/releases/24.04/current/"
    "ubuntu-noble-wsl-amd64-wsl.rootfs.tar.gz"
)
ROOTFS = WSL_DIR / "ubuntu-noble-wsl-amd64.rootfs.tar.gz"
ADB = os.environ.get("ADB") or r"D:\Android\sdk\platform-tools\adb.exe"
PACKAGE = "org.johncarter.chesspuz"
ACTIVITY = "org.kivy.android.PythonActivity"
COPY_DIRS = ("chesspuz",)
COPY_FILES = ("manifest_application_args.xml",)
IGNORE = shutil.ignore_patterns("__pycache__", "*.pyc", ".pytest_cache", "tests")
MAIN_STUB = '''"""chesspuz - Android entry (generated by android/sync.py; see mobile/entry.py)."""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mobile.entry import main

if __name__ == "__main__":
    sys.exit(main())
'''
INTERESTING = re.compile(
    r"(?i)error|exception|traceback|failed|warning: |apk|available in|\[DEPLOY\]|"
    r"building |downloading|unpacking|installing|need |not found|stderr|"
    r"^\[|^== |compiling|distribution|bootstrap|recipe"
)
# logcat -v time lines from the app itself: "09-23 12:48:35.216 I/python  (10768): ..."
LOG_PATTERN = re.compile(
    r"^\S+ \S+ [A-Z]/(python|PythonActivity|Qt\w*|qt\.[\w.]*|AndroidRuntime|DEBUG|libc)\s*\("
    r"|Traceback|^\S+ \S+ [A-Z]/\S+\s*\(\s*\d+\):\s+File \""
)


def log(msg: str) -> None:
    print(f"[sync] {msg}", flush=True)


def decode(raw: bytes) -> str:
    """wsl.exe talks UTF-16 for its own messages, the Linux side UTF-8."""
    if b"\x00" in raw:
        return raw.decode("utf-16-le", "ignore").replace("\x00", "")
    return raw.decode("utf-8", "replace")


def run(cmd, check=True, capture=False, **kw):
    if capture:
        p = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, **kw)
        out = decode(p.stdout)
        if check and p.returncode:
            raise SystemExit(f"command failed ({p.returncode}): {' '.join(map(str, cmd))}\n{out}")
        return out
    p = subprocess.run(cmd, **kw)
    if check and p.returncode:
        raise SystemExit(f"command failed ({p.returncode}): {' '.join(map(str, cmd))}")
    return p.returncode


def stream(cmd, logfile=None, verbose=True) -> int:
    """Run cmd, print its output live (all of it, or the interesting lines plus a heartbeat)
    and keep everything in logfile."""
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    fh = open(logfile, "w", encoding="utf-8") if logfile else None
    n = 0
    assert proc.stdout is not None
    for raw in iter(proc.stdout.readline, b""):
        line = decode(raw).rstrip("\r\n")
        n += 1
        if fh:
            fh.write(line + "\n")
            fh.flush()  # tail-able while the build runs
        if verbose or INTERESTING.search(line):
            print(line, flush=True)
        elif n % 250 == 0:
            print(f"[sync] ... {n} lines ({datetime.now():%H:%M:%S})", flush=True)
    proc.wait()
    if fh:
        fh.close()
    return proc.returncode


def wsl_path(p) -> str:
    p = Path(p).resolve()
    return "/mnt/" + p.drive[0].lower() + p.as_posix()[2:]


def wsl_distros() -> list[str]:
    out = run(["wsl", "-l", "-q"], check=False, capture=True)
    return [line.strip() for line in out.splitlines() if line.strip()]


def wsl_bash(script: str, env=None, logfile=None, verbose=True) -> int:
    """Run android/wsl/<script> inside the build box as root (CRLF-safe). Parameters travel
    as environment assignments inside the command string: `wsl -- bash -c script args`
    silently drops positional arguments."""
    src = wsl_path(AND / "wsl" / script)
    assigns = " ".join(f"{k}='{v}'" for k, v in (env or {}).items())
    inner = f"tr -d '\\r' < '{src}' > /tmp/cp_{script} && {assigns} bash /tmp/cp_{script}"
    cmd = ["wsl", "-d", DISTRO, "-u", "root", "--", "bash", "-c", inner]
    return stream(cmd, logfile=logfile, verbose=verbose)


# ---- steps --------------------------------------------------------------------------


def read_version() -> str:
    p = AND / "VERSION"
    return p.read_text().strip() if p.exists() else "0.1.0"


def bump_version(explicit=None, bump=True) -> str:
    cur = read_version()
    if explicit:
        new = explicit
    elif bump:
        parts = cur.split(".")
        parts[-1] = str(int(re.sub(r"\D", "", parts[-1]) or 0) + 1)
        new = ".".join(parts)
    else:
        new = cur
    (AND / "VERSION").write_text(new + "\n")
    return new


def git_stamp() -> str:
    try:
        rev = (
            subprocess.run(
                ["git", "rev-parse", "--short", "HEAD"],
                cwd=ROOT,
                capture_output=True,
                text=True,
                timeout=10,
            ).stdout.strip()
            or "nogit"
        )
        dirty = subprocess.run(
            ["git", "status", "--porcelain", "--", ".", ":!android/app"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            timeout=10,
        ).stdout.strip()
        return rev + ("+" if dirty else "")
    except Exception:  # noqa: BLE001 (git is optional here)
        return "nogit"


def make_icon(force=False) -> None:
    """android/icon.png: the white knight on a dark rounded square, 512 px, drawn once."""
    icon = AND / "icon.png"
    if icon.exists() and not force:
        return
    os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
    sys.path.insert(0, str(ROOT))
    import chess
    from PySide6.QtCore import QRectF, Qt
    from PySide6.QtGui import QColor, QImage, QPainter, QPen
    from PySide6.QtWidgets import QApplication

    from chesspuz.ui.pieces import PieceCache

    app = QApplication.instance() or QApplication([])
    size = 512
    image = QImage(size, size, QImage.Format.Format_ARGB32)
    image.fill(Qt.GlobalColor.transparent)
    painter = QPainter(image)
    painter.setRenderHint(QPainter.RenderHint.Antialiasing)
    painter.setPen(QPen(QColor("#5f6368"), 10))
    painter.setBrush(QColor("#202124"))
    painter.drawRoundedRect(QRectF(8, 8, size - 16, size - 16), 96, 96)
    # a hint of the board behind the knight
    for i in range(4):
        for j in range(4):
            if (i + j) % 2:
                painter.fillRect(QRectF(64 + i * 96, 64 + j * 96, 96, 96), QColor("#769656"))
            else:
                painter.fillRect(QRectF(64 + i * 96, 64 + j * 96, 96, 96), QColor("#eeeed2"))
    knight = PieceCache().pixmap(chess.Piece(chess.KNIGHT, chess.WHITE), 400)
    painter.drawPixmap(56, 56, knight)
    painter.end()
    if not image.save(str(icon), "PNG"):
        raise SystemExit(f"could not write {icon}")
    del app
    log(f"drew {icon.name}")


def find_db(args) -> Path | None:
    if args.no_db:
        return None
    if args.db:
        return Path(args.db)
    sys.path.insert(0, str(ROOT))
    from chesspuz import paths

    return paths.puzzle_db_path()


def step_sync(args) -> str:
    version = bump_version(args.version, bump=not args.no_bump)
    if APP.exists():
        shutil.rmtree(APP)
    APP.mkdir(parents=True)
    for name in COPY_DIRS:
        shutil.copytree(ROOT / name, APP / name, ignore=IGNORE)
    for name in COPY_FILES:
        shutil.copy2(AND / name, APP / name)
    shutil.copytree(AND / "mobile", APP / "mobile", ignore=IGNORE)
    (APP / "main.py").write_text(MAIN_STUB, encoding="utf-8")
    stamp = git_stamp()
    (APP / "mobile" / "build_info.py").write_text(
        f'VERSION = "{version}"\nCOMMIT = "{stamp}"\nBUILT = "{datetime.now():%Y-%m-%d %H:%M}"\n',
        encoding="utf-8",
    )
    make_icon()
    shutil.copy2(AND / "icon.png", APP / "icon.png")
    db = find_db(args)
    if db is not None and db.exists():
        shutil.copy2(db, APP / "puzzles.sqlite")
        log(f"bundled {db} ({db.stat().st_size / 1e6:.1f} MB)")
    else:
        log("no puzzle database bundled" + (f" ({db} is missing)" if db else ""))
    n = sum(1 for p in APP.rglob("*") if p.is_file())
    log(f"android/app refreshed: {n} files, version {version} ({stamp})")
    return version


def step_setup(args) -> None:
    if DISTRO in wsl_distros():
        log(f"WSL distro {DISTRO} exists")
    else:
        WSL_DIR.mkdir(parents=True, exist_ok=True)
        if not ROOTFS.exists():
            log(f"downloading Ubuntu 24.04 rootfs (~360 MB) to {ROOTFS}")
            urllib.request.urlretrieve(ROOTFS_URL, ROOTFS)
        log(f"importing {DISTRO} into {WSL_DIR / DISTRO}")
        run(["wsl", "--import", DISTRO, str(WSL_DIR / DISTRO), str(ROOTFS), "--version", "2"])
    log("installing the toolchain (a few minutes the first time)")
    rc = wsl_bash("setup.sh", verbose=True)
    if rc:
        raise SystemExit(f"setup failed ({rc})")
    log("release signing key (created once, backed up to D:\\Claude\\secrets)")
    rc = wsl_bash("keystore.sh", verbose=True)
    if rc:
        raise SystemExit(f"keystore setup failed ({rc})")


def step_build(args) -> None:
    if DISTRO not in wsl_distros():
        raise SystemExit(f"no WSL distro {DISTRO}: run  python android\\sync.py setup  first")
    if not APP.exists():
        step_sync(args)
    t0 = time.time()
    log(f"building in {DISTRO} (log: android/build.log)")
    rc = wsl_bash(
        "build.sh",
        {"CP_SRC": wsl_path(AND), "CP_MODE": "debug" if args.debug else "release"},
        logfile=AND / "build.log",
        verbose=args.verbose,
    )
    mins = (time.time() - t0) / 60
    if rc:
        raise SystemExit(f"build failed ({rc}) after {mins:.1f} min - see android/build.log")
    apk = newest_apk()
    if apk:
        log(f"built in {mins:.1f} min: {apk} ({apk.stat().st_size / 1e6:.1f} MB)")
    else:
        log("no APK produced?")


def step_clean(args) -> None:
    rc = wsl_bash("build.sh", {"CP_SRC": wsl_path(AND), "CP_MODE": "clean"})
    if rc:
        raise SystemExit(f"clean failed ({rc})")


def newest_apk() -> Path | None:
    folder = AND / "bin"
    if not folder.exists():
        return None
    apks = sorted(folder.glob("*.apk"), key=lambda p: p.stat().st_mtime)
    return apks[-1] if apks else None


def adb(*a, serial=None, check=True, capture=True, **kw):
    cmd = [ADB] + (["-s", serial] if serial else []) + list(a)
    return run(cmd, check=check, capture=capture, **kw)


def device_state(serial=None):
    out = adb("devices", serial=None, check=False)
    rows = [line.split() for line in out.splitlines()[1:] if line.strip()]
    if serial:
        rows = [r for r in rows if r[0] == serial]
    if not rows:
        return None, "no device (plug the phone in, USB debugging on)"
    return rows[0][0], rows[0][1]


def step_install(args) -> None:
    apk = newest_apk()
    if apk is None:
        raise SystemExit("no APK in android/bin: run  python android\\sync.py build")
    serial, state = device_state(args.serial)
    if state != "device":
        raise SystemExit(
            f"phone not ready: {state} (accept the USB debugging prompt on the phone, then retry)"
        )
    log(f"installing {apk.name} on {serial}")
    out = adb("install", "-r", "-d", str(apk), serial=serial, check=False)
    if "INSTALL_FAILED_UPDATE_INCOMPATIBLE" in out:
        # the installed app was signed with another key (debug build vs release build):
        # Android refuses the update, so the old app goes, and its runs and settings with it
        log("signed with another key than the installed app: uninstalling it (phone data is lost)")
        print(adb("uninstall", PACKAGE, serial=serial, check=False).strip())
        out = adb("install", "-r", "-d", str(apk), serial=serial, check=False)
    print(out.strip())
    if "Success" not in out:
        raise SystemExit("adb install did not report Success")


def step_run(args) -> None:
    serial, state = device_state(args.serial)
    if state != "device":
        raise SystemExit(f"phone not ready: {state}")
    adb("shell", "am", "force-stop", PACKAGE, serial=serial, check=False)
    adb("logcat", "-c", serial=serial, check=False)
    out = adb("shell", "am", "start", "-n", f"{PACKAGE}/{ACTIVITY}", serial=serial)
    print(out.strip())
    log("launched; give it ~10 s, then  python android\\sync.py logs")


def step_logs(args) -> None:
    serial, state = device_state(args.serial)
    if state != "device":
        raise SystemExit(f"phone not ready: {state}")
    cmd = [ADB, "-s", serial, "logcat", "-v", "time"]
    if args.follow:
        log(f"following logcat for {args.follow} s")
        try:
            p = subprocess.run(
                cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=args.follow
            )
            out = p.stdout
        except subprocess.TimeoutExpired as exc:
            out = exc.stdout or b""
    else:
        out = subprocess.run(cmd + ["-d"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT).stdout
    lines = [line for line in decode(out).splitlines() if LOG_PATTERN.search(line)]
    print("\n".join(lines[-400:]))
    if any("Traceback" in line for line in lines):
        log("a Python traceback is in the log above")


def step_status(args) -> None:
    serial, state = device_state(args.serial)
    print(f"phone        : {serial or '-'} {state}")
    have = DISTRO in wsl_distros()
    print(f"WSL build box: {'present' if have else 'missing (run setup)'} ({WSL_DIR / DISTRO})")
    if have:
        rc = subprocess.run(
            ["wsl", "-d", DISTRO, "-u", "root", "--", "test", "-f", "/root/.chesspuz-setup-done"]
        ).returncode
        print(f"toolchain    : {'installed' if rc == 0 else 'not installed (run setup)'}")
    apk = newest_apk()
    print(f"VERSION      : {read_version()}   app/: {'synced' if APP.exists() else 'not synced'}")
    if apk:
        when = datetime.fromtimestamp(apk.stat().st_mtime)
        size = f"{apk.stat().st_size / 1e6:.1f} MB"
        print(f"latest APK   : {apk.name}  ({size}, {when:%Y-%m-%d %H:%M})")
    else:
        print("latest APK   : -")


STEPS = {
    "sync": step_sync,
    "setup": step_setup,
    "build": step_build,
    "clean": step_clean,
    "install": step_install,
    "run": step_run,
    "logs": step_logs,
    "status": step_status,
}


def main(argv=None) -> int:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument(
        "steps",
        nargs="*",
        default=["sync"],
        help="sync setup build clean install run logs status all",
    )
    p.add_argument("--version", default=None, help="set android/VERSION (else the patch bumps)")
    p.add_argument("--no-bump", action="store_true", help="keep the current VERSION on sync")
    p.add_argument("--no-db", action="store_true", help="do not bundle the puzzle database")
    p.add_argument("--db", default=None, help="bundle this puzzle database (default: the app's)")
    p.add_argument("--debug", action="store_true", help="build a debuggable APK (default: release)")
    p.add_argument("--serial", default=None, help="adb device serial")
    p.add_argument("--follow", type=int, default=0, help="logs: follow logcat for N seconds")
    p.add_argument("--verbose", action="store_true", help="build: print every line")
    args = p.parse_args(argv)
    steps: list[str] = []
    for s in args.steps:
        if s == "all":
            steps += ["sync", "build", "install", "run", "logs"]
        elif s in STEPS:
            steps.append(s)
        else:
            p.error(f"unknown step {s!r}")
    for s in steps:
        if s == "logs" and "run" in steps and not args.follow:
            time.sleep(10)  # let the app start before dumping the log
        STEPS[s](args)
    return 0


if __name__ == "__main__":
    sys.exit(main())
